function Hd = filtro_PA
%FILTRO_PA Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 28-Apr-2022 15:38:55

% Equiripple Highpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 2048;  % Sampling Frequency

Fstop = 3;               % Stopband Frequency
Fpass = 5;               % Passband Frequency
Dstop = 0.031622776602;  % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop, Fpass]/(Fs/2), [0 1], [Dstop, Dpass]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
