function Hd = passa_alto_5Hz
%PASSA_ALTO_5HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
% Generated on: 06-Mar-2026 20:02:26

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 2048;  % Sampling Frequency

Fstop = 4.5;         % Stopband Frequency
Fpass = 5;           % Passband Frequency
Astop = 80;          % Stopband Attenuation (dB)
Apass = 1;           % Passband Ripple (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
